### ISSUE TITLE
Gifs implementieren?

### ISSUE THREAD

**Issue by Astrothewhiteshadow** [nalsai/nalsai.de#20]
Könntest du vielleicht Gifs implementieren? Ich glaube dass würde die Website deutlich verbessern!

**Comment by nalsai** [comment]
Alle modernen Browser unterstützen bereits GIFs, daher ist es nicht notwendig, sie speziell zu implementieren. Außerdem bieten alternative Formate wie APNG, WebP, AVIF oder andere Videoformate eine bessere Bildqualität bei kleineren Dateigrößen im Vergleich zu GIFs.

Jedoch ist es eine gute Idee, darüber nachzudenken, wie die Medien auf der Website verbessert werden könnten. Wenn du einen konkreten Vorschlag hast, kannst du dafür gerne ein neues Issue öffnen.
